name: container-build

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  PANDOC_VERSION: 3.1.8

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [tectonic, texlive, typst]
    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: arch-pandoc
          tags: |
            ${{ matrix.type == 'tectonic' && 'latest' }}
            ${{ matrix.type }}
            ${{ env.PANDOC_VERSION }}-${{ matrix.type }}
          containerfiles: ./Dockerfile.${{ matrix.type }}
          build-args: |
            PANDOC_VERSION=${{ env.PANDOC_VERSION }}
          oci: true
          layers: true
          extra-args:
            --cache-from ghcr.io/${{ github.repository_owner }}/arch-pandoc

      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push-ghcr
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: |
            ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Push To Docker Hub
        uses: redhat-actions/push-to-registry@v2
        id: push-docker
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: |
            ${{ steps.build_image.outputs.tags }}
          registry: docker.io/${{ secrets.DOCKERHUB_USERNAME }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
